version: '3.4'

services:
  nginx:
    build:
      context: 'docker/nginx'
    depends_on:
      - 'php'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './public:/srv/website/public:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  php:
    build:
      context: 'docker/php'
    volumes:
      - './:/srv/website:rw,cached'
    depends_on:
      - 'mysql'
    user: 'www-data:www-data'

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'github'
      MYSQL_USER: 'github'
      MYSQL_PASSWORD: 'github'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'

  adminer:
    image: 'adminer'
    depends_on:
      - 'mysql'
    ports:
      - '8081:8080'

  encore:
    build:
      context: 'docker/encore'
    volumes:
      - './:/usr/src/app'
    ports:
      - "8080:8080"

volumes:
  db-data:
